num_workers: 0

worker_heap_limit_mb: 250

logging:
  level: warn

metrics:
  type: log

services:
  - name: citoid
    module: ./app.js
    conf:
      port: 1970
      cors: '*'
      userAgent: null
      zotero: true
      zoteroInterface: zotero
      zoteroPort: 1969
      zoteroUseProxy: false
      xisbn: false
      allowPrivateAddresses: false
      maxRedirects: 5
      mwapi_req:
        method: post
        uri: https://{{domain}}/w/api.php
        headers:
          user-agent: '{{user-agent}}'
        body: '{{ default(request.query, {}) }}'
