version: '3'

services:
  citoid:
    image: droidwiki/citoid
    ports:
      - "172.16.0.2:1970:1970"
    volumes:
      - ./citoid/config.yml:/bin/config.yml

  zotero:
    image: zotero/translation-server

  parsoid:
    image: thenets/parsoid:0.10
    ports:
      - "172.16.0.2:8142:8000"
    volumes:
      - ./parsoid/config.yml:/var/lib/parsoid/config.yaml
    working_dir: /var/lib/parsoid
    command: "su -c 'node bin/server.js' parsoid"
