version: '3'

services:
  citoid:
    image: droidwiki/citoid
    depends_on:
      - zotero
    volumes:
      - ./citoid/config.yml:/bin/config.yml

  zotero:
    image: zotero/translation-server

  parsoid:
    image: droidwiki/parsoid
    volumes:
      - ./parsoid/config.yml:/bin/config.yaml

  restbase:
    image: droidwiki/restbase
    depends_on:
      - citoid
      - parsoid
    ports:
      - "172.0.0.2:7231:7231"
    volumes:
      - ./restbase/config.yaml:/restbase/config.yaml
      - ./restbase/droidwiki.yaml:/restbase/projects/droidwiki.yaml
      - ./restbase/droidwiki_sys.yaml:/restbase/projects/sys/droidwiki.yaml
