openapi: 3.0.1
info:
  version: 1.0.0
  title: DroidWiki REST API
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
x-host-basePath: /api/v1
x-route-filters:
  - path: lib/content_location_filter.js
  - path: ./lib/normalize_title_filter.js
    options:
      redirect_cache_control: '{{options.purged_cache_control}}'

paths:
  /page:
    x-modules:
      - path: v1/content.yaml
        options:
          response_cache_control: '{{options.purged_cache_control}}'
      - path: v1/common_schemas.yaml # Doesn't really matter where to mount it.
      - path: v1/related.js
        options: '{{options.related}}'
  /transform:
    x-modules:
      - path: v1/transform.yaml
  /data:
    x-modules:
      - path: v1/citoid.js
        options: '{{options.citoid}}'
