worker_heartbeat_timeout: 300000
logging:
    level: info
services:
  - module: lib/index.js
    entrypoint: apiServiceWorker
    conf:
        mwApis:
          - droidwikiwiki:
            uri: 'https://www.droidwiki.org/w/api.php'
            prefix: 'droidwikiwiki'
          - endroidwikiwiki:
            uri: 'https://en.droidwiki.org/w/api.php'
            prefix: 'endroidwikiwiki'
          - opswiki:
            uri: 'http://ops.go2tech.de/w/api.php'
            prefix: 'opswiki'
          - datawiki:
            uri: 'https://data.droidwiki.org/w/api.php'
            prefix: 'datawiki'
        useSelser: true

